title: Pangrj
SEOTitle: Pangrj
email: pangrj@buaa.edu.cn
description: "Pangrj's academic homepage"
url: "https://pangrj.github.io"
theme: jekyll-theme-minimal
deploy:
  type: git
  repository: git@github.com:pangrj/phiaiPage.git
  branch: main
